### ISSUE TITLE
Importing the ProgrammingAndroid2Examples Projects To Eclipse . . . 

### ISSUE THREAD

**Issue by corinthian13** [bmeike/ProgrammingAndroid2Examples#10]
1. The Eclipse import function renames the project to whatever name the main activity has.
2. Some projects in the folder are simply not "seen" by the import feature, e.g. ClientServerDemo, FillListTask and SharedListTask.
3. There is a Java error in the MicroJobs project. Looks like some required library is not appended to the project.
4. How come all these issues weren't sorted out by either the FOUR EXPERT authors or by their publisher's editor at O'Reilly before publishing the SECOND edition ?

**Comment by bmeike** [comment]
Hey Corinthian13
  In reverse order!
1.  The issues you describe _WERE_ sorted out by the 4 Android experts that wrote the book!  We expected, exactly, problems like this and did our best to address them.  Our book, though, is about Android, not about Eclipse.  We did not cover every issue that could be encountered by every newcomer to the platform.
2. Please read through the book chapter on this project.  You are correct: it takes some extra configuration to get the project to build.  The extra configuration, though, is described in detail, in the book.
3. It is true!  There are projects here that are not immediately importable!  Please read the book for a description of what those projects are, and how to use them
4. You are using Import >> Android >> Existing Android Code into Workspace, instead of Import >> General >> Existing Projects into Workspace, as our directions recommend.  Try doing it our way.  It works better.

**Comment by corinthian13** [comment]
Christ, you're quick enough to close threads, aren't you ?
<< You are using Import >> Android >> Existing Android Code into Workspace, instead of Import >> General >> Existing Projects into Workspace, as our directions recommend. Try doing it our way. It works better. >>
Where were such directions given ?
In the book ?
In the README file for your download site ?

I'd love to try it your way.
But I don't see how.
And others - see Stackoverflow forum on this very issue - apparently haven't either.

**Comment by bmeike** [comment]
On May 31, 2014, at 7:25 AM, corinthian13 notifications@github.com wrote:

> Christ, you're quick enough to close threads, aren't you ?
> << You are using Import >> Android >> Existing Android Code into Workspace, instead of Import >> General >> Existing Projects into Workspace, as our directions recommend. Try doing it our way. It works better. >>
> Where were such directions given ?
> In the book ?
> In the README file for your download site ?

As I said, our book is about Android, not about Eclipse.  There are some great Eclipse books out there, if you are interested.

You are quite correct, though, that we do not describe in detail, how to do this.  We have to start somewhere.

> I'd love to try it your way.
> But I don't see how.
> And others - see Stackoverflow forum on this very issue - apparently haven't either.

Please cite a specific Stack Overflow issue.  I’ll address the problem there.

-blake

**Comment by paulvi** [comment]
> Please cite a specific Stack Overflow issue.  I’ll address the problem there.

:+1:

**Comment by corinthian13** [comment]
It's not on importing your book's projects specifically but importing Android projects in general :

http://stackoverflow.com/questions/14836776/importing-existing-android-project-into-eclipse-renames-project

**Comment by bmeike** [comment]
Thanks very much!!  I’ll check this right out.

-blake
